### ISSUE TITLE
How to use Custom view

### ISSUE THREAD

**Issue by NavjotSinghSeraphic** [SimformSolutionsPvtLtd/SSPullToRefresh#42]
@tejas-ardeshna  @yashwantGowla  @BirjuVachhani  
How to use Custom view
can you give us example

**Comment by nishchal-v** [comment]
@NavjotSinghSeraphic In order to use the custom views you can refer to this [WaveAnimation](https://github.com/SimformSolutionsPvtLtd/SSPullToRefresh/blob/main/app/src/main/java/com/simform/pulltorefresh/WaveAnimation.kt) view.
Moreover you can refer to README file to better understand how to set the custom view.

**Comment by NavjotSinghSeraphic** [comment]
@nishchal-v     may i know  how to use this  at bottom while implementing pagination

**Comment by nishchal-v** [comment]
@NavjotSinghSeraphic SSPullToRefresh currently do not support bottom refresh.
